### ISSUE TITLE
Bug in load SBML with layout?

### ISSUE THREAD

**Issue by hsauro** [0u812/sbnw#38]
I created this SBML model with layout information using version 0.4.6 of the library. However when I load it back in I get a the following errors:

Failed to parse SBML
Error 0: Missing a required XML attribute. The species attribute 'compartment' is required.
Error 1: Missing a required XML attribute. The species attribute 'compartment' is required.
Error 2: Missing a required XML attribute. The species attribute 'compartment' is required.
Error 3: Missing a required XML attribute. The species attribute 'compartment' is required.
Error 4: Missing a required XML attribute. The species attribute 'compartment' is required.
Error 5: Missing a required XML attribute. The species attribute 'compartment' is required.
Error 6: Missing a required XML attribute. The species attribute 'compartment' is required.

Looks like the species tag doesn't have a compartment. I checked the sbml validator and the file is an invalid sbml file. The original file fro which I generated it does have species with a compartment. The SBML generated by sbnw doesn't include a compartment which I think it should have.

Model file attached to issue. Chance the extension of the file to xml.

[_testLayoutWithLayout .txt](https://github.com/0u812/sbnw/files/18149/_testLayoutWithLayout.txt)

**Comment by 0u812** [comment]
This issue was moved to sys-bio/sbnw#17
