### ISSUE TITLE
Does gravity actually do anything?

### ISSUE THREAD

**Issue by hsauro** [0u812/sbnw#39]
I was experimenting with gravity but I don't seem observe anything happening when I try to use it. I'm using it this way:

options.gravity := gravity;
doLayoutAlgorithm (options, layoutInfo);
network = gf_getNetwork (layoutInfo);

then I call methods to get the network information to render in on screen. What is the range of value for gravity, I am currently trying 0 to 2000. I enclose the file I tried it on.

**Comment by 0u812** [comment]
This issue was moved to sys-bio/sbnw#16
