### ISSUE TITLE
What is the end point in the call to gf_curveCP gf_getCurveCPs

### ISSUE THREAD

**Issue by hsauro** [0u812/sbnw#43]
A call to gf_curveCP gf_getCurveCPs (i, j) obtains the coords for the jth curve in the ith reaction. For the curve that is drawn to the product, what is the end point coordinate, is it the center of the product node? Is there a way to get the coordinate just before the curve reaches the node? This would make it convenient to add the arrow if I knew this coordinate. From my own experiments, the end point for  the curve that goes to a product node appears to end at the enter of the node? The docs are not clear on this.

**Comment by 0u812** [comment]
This issue was moved to sys-bio/sbnw#12
