### ISSUE TITLE
How does one use gf_loadSBMLIntoLayoutEngine

### ISSUE THREAD

**Issue by hsauro** [0u812/sbnw#46]
Not entirely sure what gf_loadSBMLIntoLayoutEngine does. How does it compare with gf_loadSBMLfile followed by gf_processLayout	. Is it a shortcut to calling these two methods but what is the argument gf_SBMLModel, docs says this is an input to the method which must come from gf_loadSBMLfile?

Hence what is the difference between:

gf_loadSBMLfile
gf_loadSBMLIntoLayoutEngine

and

gf_loadSBMLfile
gf_processLayout

**Comment by 0u812** [comment]
This issue was moved to sys-bio/sbnw#9
