### ISSUE TITLE
Summarize difference with these three pointers

### ISSUE THREAD

**Issue by hsauro** [0u812/sbnw#47]
Looking through the methods I noticed at least three different kinds of pointers that refer to the model/layout/network, ie

gf_SBMLModel
gf_network
gf_layoutInfo

what is the difference between the three of them, do we need all three of them, could they be consolidated into one pointer to simplify things? In particular the difference between gf_network and gf_layoutInfo isn't clear to me.

**Comment by 0u812** [comment]
This issue was moved to sys-bio/sbnw#8
