### ISSUE TITLE
Need docs on how to deal with errors

### ISSUE THREAD

**Issue by hsauro** [0u812/sbnw#48]
There is no mention in the docs about what happens if there is an error during a call. Eg some methods such as

int gf_renderTikZFile (gf_layoutInfo *l, const char *filename)

return an integer which presumably indicates an error if the return value is 0 ?

For some methods I am unsure what the error condition is. Eg for the method:

gf_SBMLModel* gf_loadSBMLbuf	(const char * buf)	

what is used to indicate that an error occurred using the loading of the SBML?

A summary of how to handle errors should be given on the main page presumably after the example.

**Comment by 0u812** [comment]
This issue was moved to sys-bio/sbnw#7
